import localFont from "next/font/local";
import "./globals.css";

import { Urbanist } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const urbanist = Urbanist({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Fluent with Amber",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        {children}
      </body>
    </html>
  );
}
